platform: linux/amd64
pipeline:
  lint:
    when:
      event:
      - pull_request
    image: node:18
    commands:
    - yarn
    - yarn lint
    #- yarn stylelint

  test:
    when:
      event:
      - pull_request
    image: node:18
    commands:
    - apt update
    - apt install firefox-esr -y --no-install-recommends
    - yarn 
    - yarn unit

  build:
    when:
      event:
      - push
      branch:
      - develop
      - stable
    image: node:18
    commands:
    - yarn
    - yarn build

  release:
    when:
      event:
      - push
      branch:
      - develop
      - stable
    image: node:18
    secrets:
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
    commands:
      - apt-get update && apt-get install -y rclone wget zip
      - wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64
      - mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli
      - chmod +x scaleway-cli
      - ./scaleway-cli object config install type=rclone
      - zip akkoma-fe.zip -r dist
      - rclone copyto akkoma-fe.zip scaleway:akkoma-updates/frontend/$CI_COMMIT_BRANCH/akkoma-fe.zip

  docs:
    when:
      event:
      - push
      branch:
      - develop
      - stable
    environment:
      CI: "true"
    image: python:3.10-slim
    secrets:
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
    commands:
    - apt-get update && apt-get install -y rclone wget git zip
    - wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64
    - mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli
    - chmod +x scaleway-cli
    - ./scaleway-cli object config install type=rclone
    - cd docs
    - pip install -r requirements.txt
    - mkdocs build
    - zip -r docs.zip site/*
    - cd site
    - rclone copy . scaleway:akkoma-docs/frontend/$CI_COMMIT_BRANCH/
